ALTER TABLE `Event`
  ADD COLUMN `splitPublicationMode` ENUM('UNRESTRICTED', 'LAST_START', 'SCHEDULED', 'DISABLED') NOT NULL DEFAULT 'UNRESTRICTED',
  ADD COLUMN `splitPublicationAt` DATETIME(3) NULL;
