services:
  api-bootstrap:
    networks:
      - app-network
      - ofeed-shared
  api:
    networks:
      - app-network
      - ofeed-shared

networks:
  ofeed-shared:
    external: true
    name: ofeed-shared
