version: '3'
services:
  mysql:
    env_file: ./.env
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    networks:
      - app-network
  api:
    image: ofeed-server
    env_file: ./server/.env
    build: ./server
    ports:
      - '${PORT}:3001'
    environment:
      - NODE_ENV=production
      - ENCRYPTION_SECRET_KEY=${ENCRYPTION_SECRET_KEY}
      - JWT_TOKEN_SECRET_KEY=${JWT_TOKEN_SECRET_KEY}
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - mysql
  frontend:
    image: ofeed-client
    env_file: ./client/.env
    build: ./client
    ports:
      - '3000:80'
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - mysql
      - api
networks:
  app-network:
    driver: bridge
