version: '3'
services:
  mysql:
    env_file: ./server/.env
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - app-network
  api:
    image: ofeed-server
    env_file: ./server/.env
    build: ./server
    ports:
      - '${SERVER_PORT}:3001'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - mysql
  frontend:
    image: ofeed-client
    env_file: ./client/.env
    build: ./client
    ports:
      - '${FRONTEND_PORT}:80'
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - mysql
      - api
networks:
  app-network:
    driver: bridge
