services:
  api:
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`${API_HOST?}`)
      - traefik.http.routers.api.entrypoints=https
      - traefik.http.routers.api.tls.certresolver=le
      - traefik.http.services.api.loadbalancer.server.port=${SERVER_PORT:-3001}
      - traefik.http.middlewares.api-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.api-redirect.redirectscheme.permanent=true
      - traefik.http.routers.api.middlewares=api-redirect
    networks:
      - app-network
      - traefik
  frontend:
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`${FRONTEND_HOST?}`)
      - traefik.http.routers.frontend.entrypoints=https
      - traefik.http.routers.frontend.tls.certresolver=le
      - traefik.http.services.frontend.loadbalancer.server.port=80
      - traefik.http.middlewares.frontend-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.frontend-redirect.redirectscheme.permanent=true
      - traefik.http.routers.frontend.middlewares=frontend-redirect
    networks:
      - app-network
      - traefik

networks:
  traefik:
    name: traefik
    external: true
