packages:
  - apps/*
  - packages/*
  - tools/*

ignoredBuiltDependencies:
  - '@apollo/protobufjs'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - argon2
  - core-js
  - esbuild
  - libxmljs2
  - prisma
