packages:
  - apps/*
  - packages/*
  - tools/*

overrides:
  vite: "^7.3.6"

minimumReleaseAge: 0

allowBuilds:
  "@prisma/engines": false
  "@swc/core": false
  argon2: false
  esbuild: false
  prisma: false
  sharp: true
  vue-demi: true
