/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as EventsEventIdIndexRouteImport } from './routes/events/$eventId/index'
import { Route as EventsEventIdSettingsRouteImport } from './routes/events/$eventId/settings'
import { Route as EventsEventIdReportRouteImport } from './routes/events/$eventId/report'
import { Route as AuthResetPasswordTokenRouteImport } from './routes/auth/reset-password/$token'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdSettingsRoute = EventsEventIdSettingsRouteImport.update({
  id: '/events/$eventId/settings',
  path: '/events/$eventId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdReportRoute = EventsEventIdReportRouteImport.update({
  id: '/events/$eventId/report',
  path: '/events/$eventId/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordTokenRoute = AuthResetPasswordTokenRouteImport.update({
  id: '/auth/reset-password/$token',
  path: '/auth/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/my-events': typeof MyEventsRoute
  '/profile': typeof ProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/events/$eventId/report': typeof EventsEventIdReportRoute
  '/events/$eventId/settings': typeof EventsEventIdSettingsRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/my-events': typeof MyEventsRoute
  '/profile': typeof ProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/events/$eventId/report': typeof EventsEventIdReportRoute
  '/events/$eventId/settings': typeof EventsEventIdSettingsRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/my-events': typeof MyEventsRoute
  '/profile': typeof ProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/events/$eventId/report': typeof EventsEventIdReportRoute
  '/events/$eventId/settings': typeof EventsEventIdSettingsRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/my-events'
    | '/profile'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/reset-password/$token'
    | '/events/$eventId/report'
    | '/events/$eventId/settings'
    | '/events/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/my-events'
    | '/profile'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/reset-password/$token'
    | '/events/$eventId/report'
    | '/events/$eventId/settings'
    | '/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/my-events'
    | '/profile'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/reset-password/$token'
    | '/events/$eventId/report'
    | '/events/$eventId/settings'
    | '/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MyEventsRoute: typeof MyEventsRoute
  ProfileRoute: typeof ProfileRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthResetPasswordTokenRoute: typeof AuthResetPasswordTokenRoute
  EventsEventIdReportRoute: typeof EventsEventIdReportRoute
  EventsEventIdSettingsRoute: typeof EventsEventIdSettingsRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/settings': {
      id: '/events/$eventId/settings'
      path: '/events/$eventId/settings'
      fullPath: '/events/$eventId/settings'
      preLoaderRoute: typeof EventsEventIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/report': {
      id: '/events/$eventId/report'
      path: '/events/$eventId/report'
      fullPath: '/events/$eventId/report'
      preLoaderRoute: typeof EventsEventIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/$token': {
      id: '/auth/reset-password/$token'
      path: '/auth/reset-password/$token'
      fullPath: '/auth/reset-password/$token'
      preLoaderRoute: typeof AuthResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MyEventsRoute: MyEventsRoute,
  ProfileRoute: ProfileRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthResetPasswordTokenRoute: AuthResetPasswordTokenRoute,
  EventsEventIdReportRoute: EventsEventIdReportRoute,
  EventsEventIdSettingsRoute: EventsEventIdSettingsRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
