#!/bin/sh
set -eu

VAULT_ENV_FILE="${VAULT_ENV_FILE:-/vault/secrets/api-env}"

if [ -f "$VAULT_ENV_FILE" ]; then
  # Values explicitly passed by Docker or Kubernetes take precedence over the
  # optional Vault Agent file. The file is generated by the trusted injector.
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
      export\ [A-Za-z_][A-Za-z0-9_]*=*)
        assignment="${line#export }"
        key="${assignment%%=*}"
        if env | grep -q "^${key}="; then
          continue
        fi
        # shellcheck disable=SC2086
        eval "export ${assignment}"
        ;;
    esac
  done < "$VAULT_ENV_FILE"
fi

exec "$@"
