name: Send commits to Discord

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - name: Notify Discord of commits to main
        run: |
          jq -c '.commits[]' "$GITHUB_EVENT_PATH" | while read -r COMMIT; do
            AUTHOR=$(echo "$COMMIT" | jq -r '.author.name')
            MESSAGE=$(echo "$COMMIT" | jq -r '.message')
            URL=$(echo "$COMMIT" | jq -r '.url')

            curl -H "Content-Type: application/json" -X POST -d "{
              \"content\": \"📦 **New Commit on \`${GITHUB_REPOSITORY}\`**\n🔀 Branch: \`${GITHUB_REF#refs/heads/}\`\n👤 Author: \`${AUTHOR}\`\n📝 Message: ${MESSAGE}\n🔗 ${URL}\"
            }" "$DISCORD_WEBHOOK"
          done
