name: Send commits to Discord

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - name: Notify Discord of commits to main
        run: |
          jq -c '.commits[]' "$GITHUB_EVENT_PATH" | while read -r COMMIT; do
            AUTHOR=$(echo "$COMMIT" | jq -r '.author.name')
            MESSAGE=$(echo "$COMMIT" | jq -r '.message')

            CONTENT=$(printf "📦 **New Commit on \`%s\`**\n🔀 Branch: \`%s\`\n👤 Author: \`%s\`\n📝 Message: %s" \
              "$GITHUB_REPOSITORY" "${GITHUB_REF#refs/heads/}" "$AUTHOR" "$MESSAGE")

            jq -n --arg content "$CONTENT" '{content: $content}' > payload.json

            curl -H "Content-Type: application/json" -X POST -d @payload.json "$DISCORD_WEBHOOK"
          done
