name: Send commits to Discord

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - name: Notify Discord of commits to main
        run: |
          jq -c '.commits[]' "$GITHUB_EVENT_PATH" | while read -r COMMIT; do
            AUTHOR=$(echo "$COMMIT" | jq -r '.author.name')
            MESSAGE=$(echo "$COMMIT" | jq -r '.message')
            URL=$(echo "$COMMIT" | jq -r '.url')

            jq -n --arg repo "$GITHUB_REPOSITORY" \
                  --arg branch "${GITHUB_REF#refs/heads/}" \
                  --arg author "$AUTHOR" \
                  --arg message "$MESSAGE" \
                  --arg url "$URL" \
                  '{
                    content: "📦 **New Commit on `" + $repo + "`**\n🔀 Branch: `" + $branch + "`\n👤 Author: `" + $author + "`\n📝 Message: " + $message + "\n🔗 " + $url
                  }' > payload.json

            curl -H "Content-Type: application/json" -X POST -d @payload.json "$DISCORD_WEBHOOK"
          done
